### ISSUE TITLE
Ease installation

### ISSUE THREAD

**Issue by kostis** [LearnLib/ralib#1]
There are actually two related issues to fix
1. The current `README` does not mention how to install `ralib` and I think it should.
2. If one guesses that perhaps installation (should) happen via `mvn install`, this command fails because `jconstraints` is not available in maven.  I think it should be.
   Alternatively, the RALib repo should specify `jconstraints` as a git submodule and include commands to fetch and build it automatically.

**Comment by fhowar** [comment]
This should be resolved.
